logging:
  level:
    org.*: error
    com.*: error

spring:
  datasource:
    url: jdbc:mysql://122.26.157.231:8706/aicp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456a?
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
